input OAuthInput {
  provider: AuthProvider!
  providerId: String!
  email: String
  fullName: String!
  profileImage: String
  role: UserRole
}

input RegisterWithEmailInput {
  fullName: String!
  email: String!
  phone: String
  password: String!
  role: UserRole!
}

input LoginWithEmailInput {
  email: String!
  password: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type SendEmailOtpPayload {
  success: Boolean!
}

type VerifyEmailPayload {
  success: Boolean!
}

input VerifyEmailInput {
  email: String!
  otp: String!
}

extend type Mutation {
  loginWithOAuth(input: OAuthInput!): AuthPayload!
  registerWithEmail(input: RegisterWithEmailInput!): AuthPayload!
  loginWithEmail(input: LoginWithEmailInput!): AuthPayload!
  sendEmailVerificationOtp(email: String!): SendEmailOtpPayload!
  verifyEmail(input: VerifyEmailInput!): VerifyEmailPayload!
}

mutation LoginWithOAuth($input: OAuthInput!) {
  loginWithOAuth(input: $input) {
    token
    user {
      id
      fullName
      email
      role
      profileImage
      authProvider
      providerId
      createdAt
      updatedAt
      emailVerified
      notificationsEnabled
      profileSetupComplete
    }
  }
}

mutation RegisterWithEmail($input: RegisterWithEmailInput!) {
  registerWithEmail(input: $input) {
    token
    user {
      id
      fullName
      email
      role
      profileImage
      authProvider
      providerId
      createdAt
      updatedAt
      emailVerified
      notificationsEnabled
      profileSetupComplete
    }
  }
}

mutation LoginWithEmail($input: LoginWithEmailInput!) {
  loginWithEmail(input: $input) {
    token
    user {
      id
      fullName
      email
      role
      profileImage
      authProvider
      providerId
      createdAt
      updatedAt
      emailVerified
      notificationsEnabled
      profileSetupComplete
    }
  }
}

mutation SendEmailVerificationOtp($email: String!) {
  sendEmailVerificationOtp(email: $email) {
    success
  }
}

mutation VerifyEmail($input: VerifyEmailInput!) {
  verifyEmail(input: $input) {
    success
  }
}
